I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 17, in script
    scene bg sketchbook with Fade(0.5)
TypeError: Fade() takes at least 3 arguments (3 given)

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 17, in script
    scene bg sketchbook with Fade(0.5)
  File "renpy/ast.py", line 1397, in execute
    renpy.exports.with_statement(trans, paired)
  File "renpy/exports.py", line 1637, in with_statement
    return renpy.game.interface.do_with(trans, paired, clear=clear)
  File "renpy/display/core.py", line 2546, in do_with
    clear=clear)
  File "renpy/display/core.py", line 3007, in interact
    repeat, rv = self.interact_core(preloads=preloads, trans_pause=trans_pause, pause=pause, pause_start=pause_start, **kwargs)
  File "renpy/display/core.py", line 3366, in interact_core
    new_widget=layers_root)
  File "renpy/curry.py", line 48, in __call__
    return self.callable(*(self.args + args), **merged_kwargs)
TypeError: Fade() takes at least 3 arguments (3 given)

Windows-10-10.0.19041
Ren'Py 7.4.2.1292
419 Project renpy 1.0
Sat Mar  6 19:52:27 2021
